"""The shipped ``04_scripts/check_package.py`` answers the tool-vocabulary question the way
the package gate does.

The package gate (``verify`` over a workspace ``package/``) runs
``sci_adk.render.paper.check_paper_tool_vocabulary`` on ``01_manuscript/main.tex`` and
``si.tex``. ``check_package.py`` is the copy a reviewer re-runs with nothing but the package
and a Python interpreter, so it cannot import sci_adk; it carries the lists itself. Its old
list still banned the bare phrase "decision rule" (standard statistics, removed from the
gate) and the bare words "verify", "Evidence" and "Claim", so the reviewer's script failed a
manuscript the gate passed. These tests pin the copy to the gate.
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

import sci_adk
from sci_adk.render import paper

_SCRIPT = (Path(sci_adk.__file__).parent / "templates" / "research-workspace" / "package"
           / "04_scripts" / "check_package.py")

# "decision rule" alone is standard statistics; the gate does not flag it.
_STATISTICS_SENTENCE = (
    "Under the decision rule, the slope supports the hypothesis when its 95% confidence "
    "interval lies within the band 0.7-1.0."
)

_SENTENCES = (
    _STATISTICS_SENTENCE,
    "A Bayes decision rule minimizes the posterior expected loss.",
    "Evidence from three independent laboratories supports the effect.",
    "Claim 2 of the patent covers the coating.",
    "To verify the model we refit it on the held-out sites.",
    "The specification of the instrument is given by the manufacturer.",
    "All results can be regenerated by running reproduce.py.",
    "The frozen decision rule was applied by the engine.",
    "The frozen Spec fixed the verdict before the data were seen.",
    "Two items were recorded: evi-fp-accuracy and claim-hyp-001.",
    "The open questions are listed in Checkpoints.md and spec_history/spec.v1.json.",
    "The sci-adk verify gate reported the record digest.",
)


def _load():
    spec = importlib.util.spec_from_file_location("check_package_under_test", _SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _patterns(compiled) -> list[tuple[str, int]]:
    return [(p.pattern, p.flags) for p in compiled]


def test_check_package_carries_the_gate_lists_verbatim():
    script = _load()
    assert tuple(script.TOOL_PHRASES) == paper._PAPER_TOOL_PHRASES
    assert _patterns([script.TOOL_WORD_RE]) == _patterns([paper._PAPER_TOOL_WORD_RE])
    assert _patterns([script.TOOL_PROPER_RE]) == _patterns([paper._PAPER_TOOL_PROPER_RE])
    assert _patterns(script.ARTIFACT_RES) == _patterns(paper._PAPER_ARTIFACT_RES)


def test_the_statistics_sentence_passes_both_checks():
    assert paper.check_paper_tool_vocabulary(_STATISTICS_SENTENCE) == []
    assert _load().toolvocab_leaks(_STATISTICS_SENTENCE) == []


@pytest.mark.parametrize("sentence", _SENTENCES)
def test_check_package_and_the_gate_report_the_same_terms(sentence):
    assert _load().toolvocab_leaks(sentence) == paper.check_paper_tool_vocabulary(sentence)


def _package(root: Path, body: str) -> Path:
    """A minimal package: the script in 04_scripts/, main.tex + si.tex + references.bib."""
    scripts = root / "04_scripts"
    scripts.mkdir(parents=True)
    shutil.copy(_SCRIPT, scripts / "check_package.py")
    manuscript = root / "01_manuscript"
    manuscript.mkdir()
    (manuscript / "main.tex").write_text(
        "\\documentclass{article}\\begin{document}\n"
        f"{body} \\cite{{Smith2020}}\n\\end{{document}}\n", encoding="utf-8")
    (manuscript / "si.tex").write_text(
        "\\documentclass{article}\\begin{document}\nSupplementary tables.\n"
        "\\end{document}\n", encoding="utf-8")
    (manuscript / "references.bib").write_text(
        "@article{Smith2020,\n  title = {A},\n  year = {2020}\n}\n", encoding="utf-8")
    return scripts / "check_package.py"


def test_the_script_passes_a_manuscript_using_the_statistics_sentence(tmp_path):
    script = _package(tmp_path, _STATISTICS_SENTENCE)
    run = subprocess.run([sys.executable, str(script)], capture_output=True, text=True,
                         cwd=tmp_path)
    assert run.returncode == 0, run.stdout + run.stderr
    assert "[main.tex] tool-vocabulary: clean" in run.stdout


def test_the_script_fails_a_manuscript_naming_the_machinery(tmp_path):
    script = _package(tmp_path, "The frozen decision rule was applied by the engine.")
    run = subprocess.run([sys.executable, str(script)], capture_output=True, text=True,
                         cwd=tmp_path)
    assert run.returncode == 1
    assert "TOOLCHAIN-VOCAB LEAK" in run.stdout
    assert "frozen decision rule" in run.stdout and "the engine" in run.stdout
